#!/usr/bin/env python
"""
Load Synthetic Data into PostgreSQL

Loads CSV files generated by scripts/generate_synthetic_data.py into a PostgreSQL database.

Features:
- Reads CSV files from data/ directory
- Validates data schema and constraints before insert
- Uses SQLAlchemy for database operations
- Transactional loading (all-or-nothing)
- Detailed logging of insert counts
- Data type validation
- Referential integrity checks
- Safety checks to prevent loading into production

Usage:
    python scripts/load_data.py
    python scripts/load_data.py --db-url postgresql://user:pass@localhost:5432/dbname
    python scripts/load_data.py --data-dir /path/to/data --db-url postgresql://...
    python scripts/load_data.py --db-url postgresql://... --force

Environment:
    DATABASE_URL - PostgreSQL connection URL (fallback)

CSV File Format (Expected):
    - users.csv: id, email, name, phone, date_of_birth, gender, country
    - financial_summary.csv: id, user_id, year, month, total_income, total_expenses, ...
    - transactions.csv: id, user_id, transaction_date, amount, category, merchant_name, ...
    - goals.csv: id, user_id, goal_name, description, target_amount, current_amount, ...
    - holdings.csv: id, user_id, ticker, quantity, average_cost, current_value, ...
    - market_prices.csv: id, ticker, price_date, open_price, close_price, ...

Validation Rules:
    - All user_id references must exist in users table
    - No null values in required columns
    - Amounts must be non-negative
    - Dates must be valid ISO format
    - Categories must match predefined list
"""

import argparse
import csv
import logging
import os
from datetime import datetime
from pathlib import Path
from typing import List, Dict, Optional
from decimal import Decimal

from sqlalchemy import create_engine, text, inspect
from sqlalchemy.exc import SQLAlchemyError, IntegrityError
import pandas as pd

# Configure logging
logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s - %(name)s - %(levelname)s - %(message)s",
)
logger = logging.getLogger(__name__)

# Expected tables and their CSV files
EXPECTED_TABLES = {
    "users": "users.csv",
    "financial_summary": "financial_summary.csv",
    "transactions": "transactions.csv",
    "goals": "goals.csv",
    "holdings": "holdings.csv",
    "market_prices": "market_prices.csv",
}

# Validation rules
VALIDATION_RULES = {
    "users": {
        "required_columns": ["id", "email", "name"],
        "nullable_columns": ["phone", "date_of_birth", "gender", "country"],
    },
    "financial_summary": {
        "required_columns": ["id", "user_id", "year", "month", "total_income"],
        "nullable_columns": [],
    },
    "transactions": {
        "required_columns": [
            "id",
            "user_id",
            "transaction_date",
            "amount",
            "category",
        ],
        "nullable_columns": ["description", "merchant_name", "is_recurring"],
    },
    "goals": {
        "required_columns": [
            "id",
            "user_id",
            "goal_name",
            "target_amount",
            "target_date",
            "goal_type",
        ],
        "nullable_columns": ["description", "status", "priority"],
    },
    "holdings": {
        "required_columns": [
            "id",
            "user_id",
            "ticker",
            "quantity",
            "average_cost",
            "current_value",
            "asset_type",
            "purchase_date",
            "last_updated",
        ],
        "nullable_columns": [],
    },
    "market_prices": {
        "required_columns": [
            "id",
            "ticker",
            "price_date",
            "open_price",
            "close_price",
            "high_price",
            "low_price",
        ],
        "nullable_columns": ["volume"],
    },
}


class DataValidator:
    """Validate CSV data before insertion."""

    def __init__(self, data_dir: str = "data/"):
        """Initialize validator with data directory.

        Args:
            data_dir: Directory containing CSV files
        """
        self.data_dir = Path(data_dir)
        self.user_ids = set()

    def validate_users_csv(self, filepath: Path) -> bool:
        """Validate users CSV file.

        Args:
            filepath: Path to users.csv

        Returns:
            True if valid, raises exception otherwise
        """
        logger.info(f"Validating {filepath.name}")

        df = pd.read_csv(filepath)

        # Check required columns
        required = VALIDATION_RULES["users"]["required_columns"]
        if not all(col in df.columns for col in required):
            raise ValueError(f"Missing required columns in users.csv: {required}")

        # Check for null values in required columns
        for col in required:
            null_count = df[col].isnull().sum()
            if null_count > 0:
                raise ValueError(f"Found {null_count} null values in required column: {col}")

        # Check email uniqueness
        if df["email"].duplicated().any():
            raise ValueError("Duplicate emails found in users.csv")

        # Store user IDs for reference validation
        self.user_ids = set(df["id"].unique())

        logger.info(f"✓ {filepath.name}: {len(df)} users, all required columns present")
        return True

    def validate_transactions_csv(self, filepath: Path) -> bool:
        """Validate transactions CSV file.

        Args:
            filepath: Path to transactions.csv

        Returns:
            True if valid, raises exception otherwise
        """
        logger.info(f"Validating {filepath.name}")

        df = pd.read_csv(filepath)

        # Check required columns
        required = VALIDATION_RULES["transactions"]["required_columns"]
        if not all(col in df.columns for col in required):
            raise ValueError(
                f"Missing required columns in transactions.csv: {required}"
            )

        # Validate amounts are positive
        if (df["amount"] <= 0).any():
            raise ValueError("Found non-positive amounts in transactions.csv")

        # Validate dates
        try:
            pd.to_datetime(df["transaction_date"])
        except Exception as e:
            raise ValueError(f"Invalid date format in transactions.csv: {e}")

        # Validate user references
        invalid_users = set(df["user_id"]) - self.user_ids
        if invalid_users:
            raise ValueError(
                f"Found transactions with invalid user_id: {invalid_users}"
            )

        logger.info(f"✓ {filepath.name}: {len(df)} transactions, all valid")
        return True

    def validate_financial_summary_csv(self, filepath: Path) -> bool:
        """Validate financial_summary CSV file."""
        logger.info(f"Validating {filepath.name}")

        df = pd.read_csv(filepath)

        # Check user references
        invalid_users = set(df["user_id"]) - self.user_ids
        if invalid_users:
            raise ValueError(
                f"Found financial summaries with invalid user_id: {invalid_users}"
            )

        # Validate amounts are non-negative
        amount_cols = ["total_income", "total_expenses", "total_savings",
                      "total_investments", "net_worth"]
        for col in amount_cols:
            if (df[col] < 0).any():
                raise ValueError(f"Found negative values in {col}")

        logger.info(f"✓ {filepath.name}: {len(df)} records, all valid")
        return True

    def validate_goals_csv(self, filepath: Path) -> bool:
        """Validate goals CSV file."""
        logger.info(f"Validating {filepath.name}")

        df = pd.read_csv(filepath)

        # Check user references
        invalid_users = set(df["user_id"]) - self.user_ids
        if invalid_users:
            raise ValueError(f"Found goals with invalid user_id: {invalid_users}")

        # Validate amounts
        if (df["target_amount"] <= 0).any():
            raise ValueError("Found non-positive target amounts in goals.csv")

        if (df["current_amount"] < 0).any():
            raise ValueError("Found negative current amounts in goals.csv")

        logger.info(f"✓ {filepath.name}: {len(df)} records, all valid")
        return True

    def validate_holdings_csv(self, filepath: Path) -> bool:
        """Validate holdings CSV file."""
        logger.info(f"Validating {filepath.name}")

        df = pd.read_csv(filepath)

        # Check user references
        invalid_users = set(df["user_id"]) - self.user_ids
        if invalid_users:
            raise ValueError(f"Found holdings with invalid user_id: {invalid_users}")

        # Validate quantities and costs
        if (df["quantity"] <= 0).any():
            raise ValueError("Found non-positive quantities in holdings.csv")

        if (df["average_cost"] <= 0).any():
            raise ValueError("Found non-positive costs in holdings.csv")

        logger.info(f"✓ {filepath.name}: {len(df)} records, all valid")
        return True

    def validate_market_prices_csv(self, filepath: Path) -> bool:
        """Validate market_prices CSV file."""
        logger.info(f"Validating {filepath.name}")

        df = pd.read_csv(filepath)

        # Validate prices
        price_cols = ["open_price", "close_price", "high_price", "low_price"]
        for col in price_cols:
            if (df[col] <= 0).any():
                raise ValueError(f"Found non-positive prices in {col}")

        if (df["high_price"] < df["low_price"]).any():
            raise ValueError("Found high_price < low_price in market_prices.csv")

        logger.info(f"✓ {filepath.name}: {len(df)} records, all valid")
        return True

    def validate_all(self) -> bool:
        """Validate all CSV files.

        Returns:
            True if all files valid
        """
        logger.info(f"\nValidating CSV files in {self.data_dir}\n")

        # Validate users first (for reference integrity)
        users_path = self.data_dir / "users.csv"
        if not users_path.exists():
            raise FileNotFoundError(f"users.csv not found: {users_path}")
        self.validate_users_csv(users_path)

        # Validate other files
        validators = {
            "financial_summary.csv": self.validate_financial_summary_csv,
            "transactions.csv": self.validate_transactions_csv,
            "goals.csv": self.validate_goals_csv,
            "holdings.csv": self.validate_holdings_csv,
            "market_prices.csv": self.validate_market_prices_csv,
        }

        for filename, validator in validators.items():
            filepath = self.data_dir / filename
            if filepath.exists():
                validator(filepath)
            else:
                logger.warning(f"⚠ {filename} not found, skipping")

        logger.info("\n✓ All CSV files validated successfully\n")
        return True


class DataLoader:
    """Load CSV data into PostgreSQL."""

    def __init__(self, db_url: str, data_dir: str = "data/"):
        """Initialize loader.

        Args:
            db_url: PostgreSQL connection URL
            data_dir: Directory with CSV files
        """
        self.db_url = db_url
        self.data_dir = Path(data_dir)
        self.engine = create_engine(db_url, echo=False)
        self.results = {
            "tables_loaded": {},
            "total_rows": 0,
            "errors": [],
        }

    def load_csv_to_table(self, csv_file: Path, table_name: str) -> int:
        """Load a CSV file into a database table.

        Args:
            csv_file: Path to CSV file
            table_name: Target table name

        Returns:
            Number of rows inserted

        Raises:
            FileNotFoundError: If CSV file not found
            SQLAlchemyError: If insert fails
        """
        if not csv_file.exists():
            logger.warning(f"⚠ {csv_file.name} not found, skipping")
            return 0

        logger.info(f"Loading {csv_file.name} → {table_name}...")

        try:
            # Read CSV
            df = pd.read_csv(csv_file)
            row_count = len(df)

            if row_count == 0:
                logger.warning(f"⚠ {csv_file.name} is empty, skipping")
                return 0

            # Clean data: replace NaN with None for SQL NULL
            df = df.where(pd.notnull(df), None)

            # Load with SQLAlchemy using to_sql
            with self.engine.begin() as conn:
                # Use if_exists='append' for demo (no upsert in basic sqlalchemy)
                df.to_sql(
                    table_name,
                    conn,
                    if_exists="append",
                    index=False,
                    method="multi",
                )

            logger.info(f"✓ Loaded {row_count} rows into {table_name}")
            self.results["tables_loaded"][table_name] = row_count
            self.results["total_rows"] += row_count

            return row_count

        except Exception as e:
            error_msg = f"Error loading {csv_file.name}: {str(e)}"
            logger.error(f"✗ {error_msg}")
            self.results["errors"].append(error_msg)
            raise

    def load_all(self) -> dict:
        """Load all CSV files into database.

        Returns:
            Dictionary with load results
        """
        # Load tables in order of dependencies
        load_order = [
            ("users.csv", "users"),
            ("financial_summary.csv", "financial_summary"),
            ("transactions.csv", "transactions"),
            ("goals.csv", "goals"),
            ("holdings.csv", "holdings"),
            ("market_prices.csv", "market_prices"),
        ]

        for csv_file, table_name in load_order:
            filepath = self.data_dir / csv_file
            try:
                self.load_csv_to_table(filepath, table_name)
            except Exception as e:
                logger.error(f"Failed to load {table_name}: {e}")
                # Continue loading other tables
                continue

        return self.results

    def verify_load(self) -> None:
        """Verify data was loaded by querying tables."""
        logger.info("\nVerifying loaded data...")

        with self.engine.connect() as conn:
            for table_name in self.results["tables_loaded"].keys():
                try:
                    result = conn.execute(
                        text(f"SELECT COUNT(*) as count FROM {table_name}")
                    )
                    count = result.scalar()
                    logger.info(f"  {table_name:25} {count:8} rows")
                except Exception as e:
                    logger.warning(f"  {table_name:25} error reading: {e}")


def is_dev_environment(db_url: str) -> bool:
    """Check if database is in dev/localhost environment."""
    return "localhost" in db_url or "127.0.0.1" in db_url or ".dev" in db_url


def load_data(db_url: str, data_dir: str = "data/", force: bool = False) -> dict:
    """Load synthetic data into database.

    Args:
        db_url: PostgreSQL connection URL
        data_dir: Directory with CSV files
        force: Skip safety confirmations

    Returns:
        Dictionary with load results
    """
    if not db_url:
        raise ValueError("Database URL not provided")

    logger.info(f"Target database: {db_url}")

    # Safety check
    if not is_dev_environment(db_url) and not force:
        logger.warning("\n⚠️  WARNING: This database does not appear to be local development!")
        logger.warning(f"   Database URL: {db_url}")
        response = input(
            "\nContinue loading data? Type 'yes' to confirm: "
        ).strip().lower()
        if response != "yes":
            logger.info("Data load cancelled")
            return {"status": "cancelled"}

    # Validate CSV files
    validator = DataValidator(data_dir=data_dir)
    try:
        validator.validate_all()
    except Exception as e:
        logger.error(f"Validation failed: {e}")
        raise

    # Load data
    loader = DataLoader(db_url, data_dir=data_dir)
    results = loader.load_all()

    # Verify
    loader.verify_load()

    return results


def main():
    """CLI entry point."""
    parser = argparse.ArgumentParser(description="Load synthetic data into PostgreSQL")
    parser.add_argument(
        "--db-url",
        type=str,
        default=None,
        help="PostgreSQL connection URL (or use DATABASE_URL env var)",
    )
    parser.add_argument(
        "--data-dir",
        type=str,
        default="data/",
        help="Directory with CSV files (default: data/)",
    )
    parser.add_argument(
        "--force",
        action="store_true",
        help="Skip safety prompts for non-dev databases",
    )

    args = parser.parse_args()

    # Get database URL
    db_url = args.db_url or os.getenv("DATABASE_URL")

    if not db_url:
        logger.error("\n✗ Error: Database URL not provided")
        logger.error("  Provide via --db-url or DATABASE_URL environment variable")
        exit(1)

    try:
        results = load_data(db_url, data_dir=args.data_dir, force=args.force)

        # Print summary
        print("\n" + "=" * 70)
        print("DATA LOAD SUMMARY")
        print("=" * 70)
        print(f"Total rows loaded:     {results.get('total_rows', 0)}")
        for table, count in results.get("tables_loaded", {}).items():
            print(f"  {table:25} {count:8} rows")
        if results.get("errors"):
            print(f"\nErrors:                {len(results['errors'])}")
            for error in results["errors"]:
                print(f"  - {error}")
        print("=" * 70 + "\n")

        exit(0)

    except Exception as e:
        logger.error(f"\n✗ Data load failed: {e}")
        exit(1)


if __name__ == "__main__":
    main()
